apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-projet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-projet
  template:
    metadata:
      labels:
        app: tp-projet
    spec:
      containers:
        - name: tp-projet-container
          image: tp-projet-2025:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
